# https://awesome-prometheus-alerts.grep.to/rules.html
groups:
  # group name
  - name: Alert
    rules:
      # alert name
      - alert: InstanceDown
        # alert condition
        expr: up == 0
        # waiting time for alert
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.instance }} : Instance Down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 30 seconds."